# Generated by Django 6.0.7 on 2026-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_group', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('license_name', models.CharField(blank=True, max_length=100)),
                ('license_url', models.URLField(blank=True)),
                ('attribution_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
