# Generated by Django 6.0.7 on 2026-08-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgm', '0001_initial'),
        ('records', '0004_record_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordBackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='bgm.backgroundmusic')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_music', to='records.record')),
            ],
        ),
    ]
