# Generated by Django 6.0.7 on 2026-08-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(upload_to='records/%Y/%m/%d/'),
        ),
    ]
