# Generated by Django 6.0.7 on 2026-08-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
