# Generated by Django 6.0.7 on 2026-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='region_1depth_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='place',
            name='sigungu_code',
            field=models.CharField(blank=True, db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(max_length=50),
        ),
    ]
